### ISSUE TITLE
Button OnClickListener fungerar inte

### ISSUE THREAD

**Issue by Therealnaxos** [Bankmongot/Pfi3_Projektarbete_Grupp2_Android#1]
På rad 86.

https://github.com/Bankmongot/Pfi3_Projektarbete_Grupp2_Android/blob/master/ScreenAndroid/src/main/java/se/mah/k3/klarappo/LoginFragment.java#L86

OnClickListener fungerar inte, den fungerade igår(och dess inann). Vi kan inte hitta lösningen... blir tokiga.

**Comment by Therealnaxos** [comment]
@k3larra

**Comment by k3larra** [comment]
mm den är fin den och dessutom mitt fel när jag felsökte.....
Ni gör toppenfint:
**View returnView = inflater.inflate(R.layout.fragment_login, container, false);**
bla bla
Men sen på sista raden....
**return inflater.inflate(R.layout.fragment_login, container, false);**
skall ju vara
**return returnView;**

Och det var jag som ändrade det när jag felsökte........ Sorry
@Therealnaxos

**Comment by Therealnaxos** [comment]
Där var den ja. Räddade oss igen, konstigt att både jag och Markus har missat det dock... 

Tackar! @k3larra
